variable2="3e-5"
: << "END"
variable1="resnet18"
python bpteAg.py "$variable1" "$variable2"
variable1="resnet50"
python bpteAg.py "$variable1" "$variable2"
variable1="resnet101"
python bpteAg.py "$variable1" "$variable2"

variable1="densenet121"
python bpteAg.py "$variable1" "$variable2"
variable1="inception_v3"
python bpteAg.py "$variable1" "$variable2"
variable1="mobilenet_v2"
python bpteAg.py "$variable1" "$variable2"
variable1="efficientnet_b1"
python bpteAg.py "$variable1" "$variable2"

variable1="vit_b_16"
python bpteAg.py "$variable1" "$variable2"
variable1="vit_l_16"
python bpteAg.py "$variable1" "$variable2"

variable1="convnext_base"
python bpteAg.py "$variable1" "$variable2"
variable1="convnext_large"
python bpteAg.py "$variable1" "$variable2"
variable1="convnext_tiny"
python bpteAg.py "$variable1" "$variable2"
END
