_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
                - 62
            "4": 3.10.13
            "5": 0.18.0
            "6": 4.44.2
            "8":
                - 5
            "12": 0.18.0
            "13": linux-x86_64
batch_size:
    value: 128
dropout:
    value: 0.5478013089843564
epochs:
    value: 5
lr:
    value: 0.001
